sudo: required
services:
  - docker

before-install:
  - docker build -t mohanprajapati/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mohanprajapati/react-test npm test

after_success:
  - docker build -t mohanprajapati/multi-client ./client
  - docker build -t mohanprajapati/multi-nginx ./nginx
  - docker build -t mohanprajapati/multi-server ./server
  - docker build -t mohanprajapati/multi-worker ./worker
  #Do Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #Upload Docker image
  - docker push mohanprajapati/multi-client
  - docker push mohanprajapati/multi-nginx
  - docker push mohanprajapati/multi-server
  - docker push mohanprajapati/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-926064184244'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY